#!/usr/bin/env bash
# Displays To infinity and beyond indefinitely
# Displays I hate the kill command when receiving a SIGTERM signal
# Displays Y U no love me?! when receiving a SIGINT signa
# delets /var/run/holbertonscript.pid when reciving SIGQUIT or SIGTERM

while true
do
	echo "To infinity and beyond"
	sleep 2
	trap 'echo "Y U no love me?!"' SIGINT
	trap 'echo "I hate the kill command" && finsher' SIGTERM
	trap 'finsher' SIGQUIT 
done
